import { AppPlatforms, Orientation } from '@/constants/enums';
import { BASE_URL } from '.';

export const projects = [
  {
    title: 'PAWs! - Live to purr',
    slug: 'paws-live-to-purr',
    description: `PAWs! is an HTML5 canvas game built with JavaScript and the Phaser Framework. PAWs' gameplay is unique throughout the
        market, it combines elements of and arcade game with ones of a puzzle game, resulting a fast-paced game that will test your
        attention, focus and adaptability to the max.`,
    image: `${BASE_URL}/static/img/apps/paws.png`,
    links: [
      { title: 'Google Play', url: 'https://play.google.com/store/apps/details?id=eu.roninmobile.paws', platform: AppPlatforms.ANDROID },
      { title: 'App Store', url: 'https://itunes.apple.com/us/app/paws!-live-to-purr/id989570749', platform: AppPlatforms.IOS },
      { title: 'Google Play', url: 'market://details?id=eu.roninmobile.paws', platform: AppPlatforms.ANDROID, isMobile: true },
      { title: 'App Store', url: 'itms-apps://itunes.apple.com/us/app/paws!-live-to-purr/id989570749', platform: AppPlatforms.IOS, isMobile: true },
    ],
    portfolio: [
      `${BASE_URL}/static/portfolio/playpaws/1.jpg`,
      `${BASE_URL}/static/portfolio/playpaws/2.jpg`,
      `${BASE_URL}/static/portfolio/playpaws/3.jpg`,
      `${BASE_URL}/static/portfolio/playpaws/4.jpg`,
      `${BASE_URL}/static/portfolio/playpaws/5.jpg`,
      `${BASE_URL}/static/portfolio/playpaws/6.jpg`,
      `${BASE_URL}/static/portfolio/playpaws/7.jpg`,
    ],
    settings: {
      xs: '100%',
      sm: '100%',
      md: '50%',
      lg: '50%',
      xl: '33.33333%',
      '2xl': '33.33333%',
      '3xl': '33.33333%',
      '4xl': '25%',
    },
    orientation: Orientation.LANDSCAPE,
  },
  {
    title: 'Save Christmas: Gift Rush',
    slug: 'save-christmas-gift-rush',
    description: 'Christmas-themed game, developed using Typescript and the Phaser Framework, available on both Android and iOS platform.',
    image: `${BASE_URL}/static/img/apps/giftrush.png`,
    links: [
      { title: 'Google Play', url: 'https://play.google.com/store/apps/details?id=eu.roninmobile.giftrush', platform: AppPlatforms.ANDROID },
      { title: 'App Store', url: 'https://itunes.apple.com/us/app/save-christmas-gift-rush/id1069632749', platform: AppPlatforms.IOS },
      { title: 'Google Play', url: 'market://details?id=eu.roninmobile.giftrush', platform: AppPlatforms.ANDROID, isMobile: true },
      {
        title: 'App Store',
        url: 'itms-apps://itunes.apple.com/us/app/save-christmas-gift-rush/id1069632749',
        platform: AppPlatforms.IOS,
        isMobile: true,
      },
    ],
    portfolio: [
      `${BASE_URL}/static/portfolio/giftrush/1.jpg`,
      `${BASE_URL}/static/portfolio/giftrush/2.jpg`,
      `${BASE_URL}/static/portfolio/giftrush/3.jpg`,
      `${BASE_URL}/static/portfolio/giftrush/4.jpg`,
      `${BASE_URL}/static/portfolio/giftrush/5.jpg`,
      `${BASE_URL}/static/portfolio/giftrush/6.jpg`,
      `${BASE_URL}/static/portfolio/giftrush/7.jpg`,
    ],
    settings: {
      xs: '100%',
      sm: '50%',
      md: '33.33333%',
      lg: '25%',
      xl: '25%',
      '2xl': '20%',
      '3xl': '20%',
      '4xl': '20%',
    },
    orientation: Orientation.PORTRAIT,
  },
  {
    title: 'Pop Pop Bubble Wrap',
    slug: 'pop-pop-bubble-wrap',
    description: `Pop Pop Bubble Wrap is a mobile game developed in Typescript with Phaser Framework, available on both Android and iOS platform. The application is a bubble wrap popping simulator that can be used for reducing one' stress and anxiety.`,
    image: `${BASE_URL}/static/img/apps/popbub.png`,
    links: [
      { title: 'Google Play', url: 'https://play.google.com/store/apps/details?id=eu.roninmobile.bubblewrap', platform: AppPlatforms.ANDROID },
      { title: 'App Store', url: 'https://itunes.apple.com/us/app/pop-pop-bubble-wrap/id1263224379?ls=1&mt=8', platform: AppPlatforms.IOS },
      { title: 'Google Play', url: 'market://details?id=eu.roninmobile.bubblewrap', platform: AppPlatforms.ANDROID, isMobile: true },
      { title: 'App Store', url: 'itms-apps://itunes.apple.com/us/app/pop-pop-bubble-wrap/id1263224379', platform: AppPlatforms.IOS, isMobile: true },
    ],
    portfolio: [
      `${BASE_URL}/static/portfolio/popbub/1.jpg`,
      `${BASE_URL}/static/portfolio/popbub/2.jpg`,
      `${BASE_URL}/static/portfolio/popbub/3.jpg`,
      `${BASE_URL}/static/portfolio/popbub/4.jpg`,
      `${BASE_URL}/static/portfolio/popbub/5.jpg`,
      `${BASE_URL}/static/portfolio/popbub/6.jpg`,
    ],
    settings: {
      xs: '100%',
      sm: '50%',
      md: '33.33333%',
      lg: '25%',
      xl: '25%',
      '2xl': '25%',
      '3xl': '20%',
      '4xl': '20%',
    },
    orientation: Orientation.PORTRAIT,
  },
  {
    title: 'Twin Dots Challenge',
    slug: 'twin-dots-challenge',
    description: `Twin Dots Challenge is a hyper-casual little puzzle, developed in TypeScript with Phaser Framework, available on both
        Android and iOS platform. For building the game for both platforms (Android & iOS) with the help of Cordova.`,
    image: `${BASE_URL}/static/img/apps/twindots.png`,
    links: [
      { title: 'Google Play', url: 'https://play.google.com/store/apps/details?id=eu.roninmobile.twindots', platform: AppPlatforms.ANDROID },
      { title: 'App Store', url: 'https://apps.apple.com/us/app/twin-dots-challenge/id1481706861', platform: AppPlatforms.IOS },
      { title: 'Google Play', url: 'market://details?id=eu.roninmobile.twindots', platform: AppPlatforms.ANDROID, isMobile: true },
      { title: 'App Store', url: 'itms-apps://itunes.apple.com/us/app/twin-dots-challenge/id1481706861', platform: AppPlatforms.IOS, isMobile: true },
    ],
    portfolio: [
      `${BASE_URL}/static/portfolio/twindots/1.jpg`,
      `${BASE_URL}/static/portfolio/twindots/2.jpg`,
      `${BASE_URL}/static/portfolio/twindots/3.jpg`,
      `${BASE_URL}/static/portfolio/twindots/4.jpg`,
      `${BASE_URL}/static/portfolio/twindots/5.jpg`,
      `${BASE_URL}/static/portfolio/twindots/6.jpg`,
      `${BASE_URL}/static/portfolio/twindots/7.jpg`,
    ],
    settings: {
      xs: '100%',
      sm: '50%',
      md: '33.33333%',
      lg: '25%',
      xl: '25%',
      '2xl': '25%',
      '3xl': '20%',
      '4xl': '20%',
    },
    orientation: Orientation.PORTRAIT,
  },
  {
    title: '13 Arrows',
    slug: '13-arrows',
    description: `13 Arrows is a hyper-casual archery game for those moments when you are bored, built with Typescript and
        Phaser Framework. Try your best to get a higher score using the arrows you have at your disposal.`,
    image: `${BASE_URL}/static/img/apps/arrows.png`,
    links: [
      { title: 'Google Play', url: 'https://play.google.com/store/apps/details?id=eu.roninmobile.arrows', platform: AppPlatforms.ANDROID },
      { title: 'App Store', url: 'https://apps.apple.com/us/app/13-arrows/id1483924074', platform: AppPlatforms.IOS },
      { title: 'Google Play', url: 'market://details?id=eu.roninmobile.arrows', platform: AppPlatforms.ANDROID, isMobile: true },
      { title: 'App Store', url: 'itms-apps://itunes.apple.com/us/app/13-arrows/id1483924074', platform: AppPlatforms.IOS, isMobile: true },
    ],
    portfolio: [
      `${BASE_URL}/static/portfolio/arrows/1.jpg`,
      `${BASE_URL}/static/portfolio/arrows/2.jpg`,
      `${BASE_URL}/static/portfolio/arrows/3.jpg`,
      `${BASE_URL}/static/portfolio/arrows/4.jpg`,
    ],
    settings: {
      xs: '100%',
      sm: '100%',
      md: '50%',
      lg: '50%',
      xl: '33.33333%',
      '2xl': '33.33333%',
      '3xl': '25%',
      '4xl': '20%',
    },
    orientation: Orientation.LANDSCAPE,
  },
];

export const socials = [
  {
    id: 'facebook',
    title: 'Facebook',
    icon: '',
    url: 'https://www.facebook.com/RoninMobile',
  },
  {
    id: 'x',
    title: 'X',
    icon: '',
    url: 'https://x.com/ronin_mobile',
  },
];
